---
server:
    install: '1'
    packages: [vim, nodejs, npm, htop, git, gcc, build-essential, curl, wget, python-software-properties, zlib1g-dev, memcached, preload, libpcre3, libpcre3-dev, unzip, dpkg-dev]
    timezone: UTC
    locale: en_GB.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: anchovy, ip: 192.168.56.105, memory: '2048', sharedfolder: ./, useVagrantCloud: '1', syncType: '0' }
nginx:
    install: '1'
    docroot: /www
    servername: anchovy.local
npm:
    install: '1'
mysql:
    install: '1'
    root_password: '123'
    database: db
    user: user
    password: password
    dump: ''
mongodb:
    install: '1'
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-mysql, php5-mongo, php5-memcache, php5-memcached, php5-xmlrpc, php5-mcrypt, php5-curl, php-pear, phpunit]
    peclpackages: [radius, mongo, memcached, memcache]
xdebug:
    install: '1'
composer:
    install: '1'

