---
- name: ensure timezone is set in cli php.ini
  lineinfile: dest=/etc/php5/cli/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ server.timezone }}'

- name: ensure realpath_cache_size is set to 4096k in cli php.ini
  lineinfile: dest=/etc/php5/cli/php.ini
              regexp=';realpath_cache_size = 16k'
              line='realpath_cache_size = 4096k'

- name: ensure realpath_cache_ttl is set to 7200 in cli php.ini
  lineinfile: dest=/etc/php5/cli/php.ini
              regexp=';realpath_cache_ttl = 120'
              line='realpath_cache_ttl = 7200'

- name: ensure max_execution_time is set to 600 in cli php.ini
  lineinfile: dest=/etc/php5/cli/php.ini
              regexp='max_execution_time = 30'
              line='max_execution_time = 600'

- name: ensure memory_limit is set to 1024 in cli php.ini
  lineinfile: dest=/etc/php5/cli/php.ini
              regexp='memory_limit = 128M'
              line='memory_limit = 1024M'

- name: enabling opcache cli
  lineinfile: dest=/etc/php5/cli/php.ini
              regexp=';?opcache.enable_cli=\d'
              line='opcache.enable_cli=1'

- name: unlink xdebug in cli
  shell: unlink  /etc/php5/cli/conf.d/20-xdebug.ini
  sudo: true