---
- name: restart php5-fpm
  service: name=php5-fpm enabled=yes state=restarted
  notify: load fixture script
  when: "'php5-fpm' == 'started'"

- name: load fixture script
  shell: /www/anchovy/bin/loadFixture.sh